# Generated by Django 4.1.5 on 2023-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('semister', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
