# Generated by Django 4.1.5 on 2023-01-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_alter_admins_email_alter_admins_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('fee', models.CharField(max_length=30)),
            ],
        ),
    ]
